# Generated by Django 4.1.1 on 2022-11-24 19:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("multi_user", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("hospital_name", models.CharField(max_length=100)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Dentistry", "Dentistry"),
                            ("Cardiology", "Cardiology"),
                            ("Astrology", "Astrology"),
                            ("Neuroanatomy", "Neuroanatomy"),
                            ("Ophthalmogoly", "Ophthalmogoly"),
                            ("Gynecology", "Gynecology"),
                        ],
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="multi_user.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="multi_user.patient",
                    ),
                ),
            ],
        ),
    ]
