from django.urls import path

from multi_user.views import (
    AdministratorRegistrationView,
    CustomAuthToken,
    DoctorListView,
    DoctorOnlyView,
    DoctorRegistrationView,
    DoctorUpdateView,
    DownloadDoctorCSVView,
    DownloadPalientCSVView,
    LastFewDoctorListView,
    LastFewPatientListView,
    LogoutView,
    PatientListView,
    PatientOnlyView,
    PatientRegistrationView,
    PatientUpdateView,
    SpecificDoctorView,
    SpecificPatientView,
    SpecificUserView,
)

app_name = "multi_user"

urlpatterns = [
    path(
        "registration/patient/",
        PatientRegistrationView.as_view(),
        name="register-patient",
    ),
    path(
        "registration/doctor/",
        DoctorRegistrationView.as_view(),
        name="register-doctor",
    ),
    path(
        "registration/administrator/",
        AdministratorRegistrationView.as_view(),
        name="register-administrator",
    ),
    path(
        "patient/dashboard/",
        PatientOnlyView.as_view(),
        name="patient-dashboard",
    ),
    path(
        "doctor/dashboard/",
        DoctorOnlyView.as_view(),
        name="doctor-dashboard",
    ),
    path(
        "logout/",
        LogoutView.as_view(),
        name="logout",
    ),
    path(
        "login/",
        CustomAuthToken.as_view(),
        name="login",
    ),
    path(
        "patient_list/",
        PatientListView.as_view(),
        name="patient-list",
    ),
    path(
        "doctor_list/",
        DoctorListView.as_view(),
        name="doctor-list",
    ),
    path(
        "last_patients_list/",
        LastFewPatientListView.as_view(),
        name="last-patients-list",
    ),
    path(
        "last_doctors_list/",
        LastFewDoctorListView.as_view(),
        name="last-doctors-list",
    ),
    path(
        "specific_patient/<int:patient_id>/",
        SpecificPatientView().as_view(),
        name="specific-patient",
    ),
    path(
        "specific_doctor/<int:doctor_id>/",
        SpecificDoctorView().as_view(),
        name="specific-doctor",
    ),
    path(
        "specific_user/<int:user_id>/",
        SpecificUserView().as_view(),
        name="specific-user",
    ),
    path(
        "doctor_update/",
        DoctorUpdateView.as_view(),
        name="doctor-update",
    ),
    path(
        "patient_update/",
        PatientUpdateView.as_view(),
        name="patient-update",
    ),
    path(
        "download_all_patients/",
        DownloadPalientCSVView.as_view(),
        name="download-all-patients",
    ),
    path(
        "download_all_doctors/",
        DownloadDoctorCSVView.as_view(),
        name="download-all-doctors",
    ),
]
